#!/bin/sh /etc/rc.common
# Copyright (C) 2013 DogHunter

START=86
STOP=86

status() {
    oi=$(pidof uSDeamon)
    if [ "x$oi" == "x" ]; then
	echo "uSDeamon is not running"
    else
	echo "uSDeamon is running ($oi)"
    fi
}

start() {
    oi=$(pidof uSDeamon)
    if [ "x$oi" == "x" ]; then
	echo "Start uSDeamon"
	/sbin/uSDeamon &
    else
	echo "uSDeamon is already running ($oi)"
    fi
}

stop() {
    kill $(pidof uSDeamon)
}

EXTRA_COMMANDS="status"
EXTRA_HELP="        status  Print the status of the service"
