#!/bin/sh
[ $# = 0 ] && { echo "  $0 <group>"; exit; }
. /etc/functions.sh

type=$1
debug "### ifdown $type ###"

if=$(nvram get ${type}_ifname)
proto=$(nvram get ${type}_proto)
if_valid $if && $DEBUG ifconfig $if down
[ -r /var/run/${if}.pid ] && kill $(cat /var/run/${if}.pid 2>&-) 2>&-
killall ifup.$proto >&- 2>&-
[ -x "/sbin/ifdown.$proto" ] && /sbin/ifdown.$proto "$type"
case "$proto" in
	pptp|pppoe) killall pppd >&- 2>&- ;;
	static) env -i ACTION="ifdown" INTERFACE="$type" PROTO=static /sbin/hotplug "iface" ;;
esac

