#!/bin/sh

TIME=2

# $1 must be a valid parameter for sleep
if [ "x$1" != "x" ];then
    TIME=$1
fi


# On start verify if the SD card is connected. If the size is 0
# it means that there is not an uSD card 
size=$(cat /sys/bus/scsi/drivers/sd/0:0:0:0/block/sda/size)
isconnected="0"
if [ "$size" != "0" ]; then
    isconnected="1"
fi

deamon()
{
    # Check the SD device
    blkid /dev/sda
    # Check if uSD card is there
    size=$(cat /sys/bus/scsi/drivers/sd/0:0:0:0/block/sda/size)
    if [ "$size" == "0" ]; then
	# If the previous run the uSD was plugged and now size is
	# 0, it means that the user un-plugged the uSD card so
	# we can unmount all uSD partitions and mark the device
	# as disconnected
	if [ "$isconnected" == "1" ]; then
	    isconnected="0"
	    for dev in $(ls /dev/sda?); do
		umount $dev
	    done
	fi
    else
	# The size is greater than 0, so mark the uSD card as
	# connected
	isconnected="1"
    fi
}

while [ true ]; do
    deamon
    sleep $TIME
done

