#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

START=80

include /lib/network

start() {
	scan_interfaces
	config_get wan_if 'wan' 'ifname'
	[ -n "$wan_if" ] || return 1
	[ -f /etc/ndyndns/ndyndns.conf ] || {
		echo "$0: missing config file '/etc/ndyndns/ndyndns.conf'" 1>&2
		return 1
	}
	service_start /usr/sbin/ndyndns -c /etc/ndyndns -f /etc/ndyndns/ndyndns.conf -i $wan_if
}

stop() {
	service_stop /usr/sbin/ndyndns
}
