#!/bin/sh
is_dirty() {
	grep Broadcom /proc/cpuinfo >&- || return 1
	OFFSET="$(($(hexdump -v /dev/mtdblock/1 -s 20 -n 2 -e '"%d"')-1))"
	return $(hexdump -v /dev/mtdblock/1 -s $OFFSET -n 1 -e '"%d"')
}

if [ "$1" != "failsafe" -a "$(nvram get no_root_swap)" != 1 ]; then 
	mtd unlock linux
	mount | grep jffs2 >&-
	if [ $? = 0 ] ; then
		if [ $(cat /proc/mtd | wc -l) = 6 ]; then
			mtd erase OpenWrt
			jffs2root --move
		else
			mount -o remount,rw /dev/root /
		fi
	else
		is_dirty
		if [ $? = 0 ]; then
			firstboot ramoverlay >&- 2>&-
		else
			mount /dev/mtdblock/4 /jffs
			pivot_root /jffs /jffs/rom && {
				mount none /proc -t proc
				umount /rom/proc
				mount -o move /rom/dev /dev
			} || {
				firstboot ramoverlay
			}
		fi
	fi
fi

mount none /tmp -t tmpfs -o nosuid,nodev,mode=1777,size=50%
mkdir -p /dev/pts
mount none /dev/pts -t devpts
mount -t sysfs none /sys 2>&-
