#!/bin/sh
case "$1" in
  start|restart)
  ifup_interfaces=$(nvram get ifup_interfaces)
  ifup_interfaces=${ifup_interfaces:-"wan lan wifi"}
  for iface in $ifup_interfaces; do
  	ifup $iface
  	if [ "$iface" = "wifi" ]; then
		$iface up
	fi
  done
  ;;
esac
