#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=50

start_service () {
	local section="$1"
	config_get address  "$section" address
	config_get password "$section" password
	config_get tunnelip "$section" tunnelip
	config_get tld      "$section" tld
	
	iodined -l $address -P $password $tunnelip $tld
}

start() {
	config_load "iodined"
	config_foreach start_service iodined
}

stop() {
	killall iodined
}
