#!/bin/sh
. /etc/functions.sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount none /proc -t proc
insmod diag
set_state preinit

ifname=eth0
# WAP54G, WL-HDD
[  "$(nvram get boardnum)" = "2" \
-o \( "$(nvram get boardnum)" = "asusX" \
   -a "$(nvram get et1phyaddr)" -eq 1 \) ] && ifname="eth1"

insmod switch-core
insmod switch-robo || insmod switch-adm || rmmod switch-core

# save the boot loader's vlan config
# we need it on some routers that have no vlan*ports set
[ -d /proc/switch/eth0 ] && {
	v0p="$(cat /proc/switch/eth0/vlan/0/ports)"
	v1p="$(cat /proc/switch/eth0/vlan/1/ports)"
	v2p="$(cat /proc/switch/eth0/vlan/2/ports)"
	echo 1 > /proc/switch/eth0/reset

	case "$(nvram get boardtype)" in
		0x0467|0x042f) echo "0 1 2 3 5u*";;
		            *) echo "1 2 3 4 5u*";;
	esac > /proc/switch/eth0/vlan/0/ports
}

ifconfig $ifname 192.168.1.1 netmask 255.255.255.0 broadcast 192.168.1.255 up
netmsg 192.168.1.0 "(dummy message)" # b44 eats the first packet
netmsg 192.168.1.255 "Press reset now, to enter Failsafe!"

echo /sbin/hotplug.failsafe > /proc/sys/kernel/hotplug
if sleep 2; then
	ifconfig $ifname 0.0.0.0

	# revert to the boot loader's vlan config
	# required for at least WRT54G v1.1
	[ -d /proc/switch/eth0 ] && {
		echo "$v0p" > /proc/switch/eth0/vlan/0/ports
		echo "$v1p" > /proc/switch/eth0/vlan/1/ports
		echo "$v2p" > /proc/switch/eth0/vlan/2/ports
	}
else
	# sleep was interrupted by a hotplug event - enter failsafe mode
	set_state failsafe
	export FAILSAFE=true
	[ "$(nvram get boot_wait)" != "on" ] && {
		nvram set boot_wait=on
		nvram commit
	}
	netmsg 192.168.1.255 "Entering Failsafe!"
	telnetd -l /bin/login <> /dev/null 2>&1
fi
echo /sbin/hotplug > /proc/sys/kernel/hotplug

mount_root ${FAILSAFE:+failsafe}

exec /sbin/init
