#!/bin/sh
[ -z "$1" ] || env -i ACTION="ifup" INTERFACE="$1" PROTO=ppp /sbin/hotplug "iface"

[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" $@
	done
}
